services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

  wp:
    image: wordpress:6.6-php8.2-apache
    depends_on: [db]
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
    volumes:
      - wp_data:/var/www/html
      - ./.docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./backups:/var/www/html/wp-content/ai1wm-backups

  wpcli:
    image: wordpress:cli-php8.2
    depends_on: [wp, db]
    user: "33:33"
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
    volumes:
      - wp_data:/var/www/html

volumes:
  db_data:
  wp_data:
